name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yaml build
        docker-compose -f docker-compose.yaml push

    - name: Add SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > my-key.pem
        chmod 400 my-key.pem
        
    - name: Copy Docker Compose File to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i my-key.pem docker-compose.yaml ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i my-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker-compose -f /docker-compose.yaml pull
          docker-compose -f /docker-compose.yaml up -d
        EOF
  
